image: node:6
stages:
  - install
  - test
prodInstall:
  stage: install
  script:
    - npm install 
  artifacts:
    untracked: true
unitTesting:
  stage: test
  script:
    - npm install
    - npm test
  