image: node:6
stages:
  - install
  - test
prodInstall:
  stage: install
  script:
    - npm install --production
  artifacts:
    untracked: true
unitTesting:
  stage: test
  dependencies:
    - prodInstall
  script:
    - npm install
    - npm test
  