export const FETCH_USER_IS_LOADING = "FETCH_USER_IS_LOADING"
export const FETCH_USER = "FETCH_USER"
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS"
export const FETCH_USER_HAS_ERROR = "FETCH_USER_HAS_ERROR"