export const FETCH_TASKS_IS_LOADING = "FETCH_TASKS_IS_LOADING"
export const FETCH_TASKS = "FETCH_TASKS"
export const FETCH_TASKS_SUCCESS = "FETCH_TASKS_SUCCESS"
export const FETCH_TASKS_HAS_ERROR = "FETCH_TASKS_HAS_ERROR"


export const CREATE_TASK_IS_LOADING = "CREATE_TASK_IS_LOADING"
export const CREATE_TASK = "CREATE_TASKS"
export const CREATE_TASKS_SUCCESS = "CREATE_TASKS_SUCCESS"
export const CREATE_TASKS_HAS_ERROR = "CREATE_TASKS_HAS_ERROR"
