export const FETCH_TASKS_IS_LOADING = "FETCH_TASKS_IS_LOADING"
export const FETCH_TASKS = "FETCH_TASKS"
export const FETCH_TASKS_SUCCESS = "FETCH_TASKS_SUCCESS"
export const FETCH_TASKS_HAS_ERROR = "FETCH_TASKS_HAS_ERROR"


