export const FETCH_TASKS_IS_LOADING = "FETCH_TASKS_IS_LOADING"
export const FETCH_TASKS_SUCCESS = "FETCH_TASKS_SUCCESS"
export const FETCH_TASKS_HAS_ERROR = "FETCH_TASKS_HAS_ERROR"

export const FETCH_TASKS_BY_DATE_SUCCESS = "FETCH_TASKS_BY_DATE_SUCCESS"
export const FETCH_TASKS_BY_DATE_HAS_ERROR = "FETCH_TASKS_BY_DATE_HAS_ERROR"

export const CREATE_CATEGORY_IS_LOADING = "CREATE_CATEGORY_IS_LOADING"
export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS"
export const CREATE_CATEGORY_HAS_ERROR = "CREATE_CATEGORY_HAS_ERROR"

export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS"
export const UPDATE_TASK_HAS_ERROR = "UPDATE_TASK_HAS_ERROR"

export const DELETE_TASK_IS_LOADING = "DELETE_TASK_IS_LOADING"
export const DELETE_TASKS_SUCCESS = "DELETE_TASKS_SUCCESS"
export const DELETE_TASKS_HAS_ERROR = "DELETE_TASKS_HAS_ERROR"